version: '2.23'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - '33060:3306'
    environment:
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: 12345
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
